// Mocks generated by Mockito 5.4.6 from annotations
// in trailrun_app/test/integration/error_handling_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i15;

import 'package:camera/camera.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trailrun_app/data/services/activity_tracking_service.dart'
    as _i6;
import 'package:trailrun_app/data/services/camera_service.dart' as _i9;
import 'package:trailrun_app/data/services/crash_recovery_service.dart' as _i7;
import 'package:trailrun_app/data/services/gps_diagnostics_service.dart' as _i5;
import 'package:trailrun_app/data/services/graceful_degradation_service.dart'
    as _i10;
import 'package:trailrun_app/data/services/location_service.dart' as _i4;
import 'package:trailrun_app/data/services/platform_permission_service.dart'
    as _i8;
import 'package:trailrun_app/domain/models/activity.dart' as _i16;
import 'package:trailrun_app/domain/models/photo.dart' as _i3;
import 'package:trailrun_app/domain/models/track_point.dart' as _i12;
import 'package:trailrun_app/domain/repositories/location_repository.dart'
    as _i2;
import 'package:trailrun_app/domain/value_objects/coordinates.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocationTrackingStats_0 extends _i1.SmartFake
    implements _i2.LocationTrackingStats {
  _FakeLocationTrackingStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhoto_1 extends _i1.SmartFake implements _i3.Photo {
  _FakePhoto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationService_2 extends _i1.SmartFake
    implements _i4.LocationService {
  _FakeLocationService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGpsDiagnostics_3 extends _i1.SmartFake
    implements _i5.GpsDiagnostics {
  _FakeGpsDiagnostics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGpsTestResult_4 extends _i1.SmartFake implements _i5.GpsTestResult {
  _FakeGpsTestResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityTrackingService_5 extends _i1.SmartFake
    implements _i6.ActivityTrackingService {
  _FakeActivityTrackingService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCrashRecoveryResult_6 extends _i1.SmartFake
    implements _i7.CrashRecoveryResult {
  _FakeCrashRecoveryResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformPermissionService_7 extends _i1.SmartFake
    implements _i8.PlatformPermissionService {
  _FakePlatformPermissionService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCameraService_8 extends _i1.SmartFake implements _i9.CameraService {
  _FakeCameraService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppCapabilities_9 extends _i1.SmartFake
    implements _i10.AppCapabilities {
  _FakeAppCapabilities_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlternativeFunctionality_10 extends _i1.SmartFake
    implements _i10.AlternativeFunctionality {
  _FakeAlternativeFunctionality_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionDenialResponse_11 extends _i1.SmartFake
    implements _i10.PermissionDenialResponse {
  _FakePermissionDenialResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDegradedTrackingOptions_12 extends _i1.SmartFake
    implements _i10.DegradedTrackingOptions {
  _FakeDegradedTrackingOptions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlatformPermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformPermissionService extends _i1.Mock
    implements _i8.PlatformPermissionService {
  MockPlatformPermissionService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i4.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocationTrackingState get trackingState => (super.noSuchMethod(
        Invocation.getter(#trackingState),
        returnValue: _i2.LocationTrackingState.stopped,
      ) as _i2.LocationTrackingState);

  @override
  _i11.Stream<_i12.TrackPoint> get locationStream => (super.noSuchMethod(
        Invocation.getter(#locationStream),
        returnValue: _i11.Stream<_i12.TrackPoint>.empty(),
      ) as _i11.Stream<_i12.TrackPoint>);

  @override
  _i11.Stream<_i2.LocationQuality> get locationQualityStream =>
      (super.noSuchMethod(
        Invocation.getter(#locationQualityStream),
        returnValue: _i11.Stream<_i2.LocationQuality>.empty(),
      ) as _i11.Stream<_i2.LocationQuality>);

  @override
  _i11.Stream<_i2.LocationTrackingState> get trackingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#trackingStateStream),
        returnValue: _i11.Stream<_i2.LocationTrackingState>.empty(),
      ) as _i11.Stream<_i2.LocationTrackingState>);

  @override
  bool get supportsBackgroundLocation => (super.noSuchMethod(
        Invocation.getter(#supportsBackgroundLocation),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<_i2.LocationPermissionStatus> getPermissionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPermissionStatus,
          [],
        ),
        returnValue: _i11.Future<_i2.LocationPermissionStatus>.value(
            _i2.LocationPermissionStatus.notRequested),
      ) as _i11.Future<_i2.LocationPermissionStatus>);

  @override
  _i11.Future<_i2.LocationPermissionStatus> requestPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i11.Future<_i2.LocationPermissionStatus>.value(
            _i2.LocationPermissionStatus.notRequested),
      ) as _i11.Future<_i2.LocationPermissionStatus>);

  @override
  _i11.Future<_i2.LocationPermissionStatus> requestBackgroundPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBackgroundPermission,
          [],
        ),
        returnValue: _i11.Future<_i2.LocationPermissionStatus>.value(
            _i2.LocationPermissionStatus.notRequested),
      ) as _i11.Future<_i2.LocationPermissionStatus>);

  @override
  _i11.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<_i13.Coordinates?> getCurrentLocation({
    _i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.balanced,
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
          {
            #accuracy: accuracy,
            #timeout: timeout,
          },
        ),
        returnValue: _i11.Future<_i13.Coordinates?>.value(),
      ) as _i11.Future<_i13.Coordinates?>);

  @override
  _i11.Future<void> startLocationTracking({
    _i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.balanced,
    int? intervalSeconds = 2,
    double? distanceFilter = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startLocationTracking,
          [],
          {
            #accuracy: accuracy,
            #intervalSeconds: intervalSeconds,
            #distanceFilter: distanceFilter,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> stopLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #stopLocationTracking,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> pauseLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #pauseLocationTracking,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> resumeLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #resumeLocationTracking,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i13.Coordinates?> getLastKnownLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLastKnownLocation,
          [],
        ),
        returnValue: _i11.Future<_i13.Coordinates?>.value(),
      ) as _i11.Future<_i13.Coordinates?>);

  @override
  _i11.Future<bool> isHighAccuracyAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isHighAccuracyAvailable,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<double> getEstimatedBatteryUsage(
          _i2.LocationAccuracy? accuracy) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEstimatedBatteryUsage,
          [accuracy],
        ),
        returnValue: _i11.Future<double>.value(0.0),
      ) as _i11.Future<double>);

  @override
  _i11.Future<void> configureFiltering({
    double? maxAccuracy = 50.0,
    double? maxSpeed = 50.0,
    bool? enableKalmanFilter = true,
    bool? enableOutlierDetection = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #configureFiltering,
          [],
          {
            #maxAccuracy: maxAccuracy,
            #maxSpeed: maxSpeed,
            #enableKalmanFilter: enableKalmanFilter,
            #enableOutlierDetection: enableOutlierDetection,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i2.LocationTrackingStats> getTrackingStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackingStats,
          [],
        ),
        returnValue: _i11.Future<_i2.LocationTrackingStats>.value(
            _FakeLocationTrackingStats_0(
          this,
          Invocation.method(
            #getTrackingStats,
            [],
          ),
        )),
      ) as _i11.Future<_i2.LocationTrackingStats>);

  @override
  _i11.Future<void> resetTrackingStats() => (super.noSuchMethod(
        Invocation.method(
          #resetTrackingStats,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void setCurrentActivityId(String? activityId) => super.noSuchMethod(
        Invocation.method(
          #setCurrentActivityId,
          [activityId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraService extends _i1.Mock implements _i9.CameraService {
  MockCameraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isCapturing => (super.noSuchMethod(
        Invocation.getter(#isCapturing),
        returnValue: false,
      ) as bool);

  @override
  _i14.FlashMode get flashMode => (super.noSuchMethod(
        Invocation.getter(#flashMode),
        returnValue: _i14.FlashMode.off,
      ) as _i14.FlashMode);

  @override
  double get zoomLevel => (super.noSuchMethod(
        Invocation.getter(#zoomLevel),
        returnValue: 0.0,
      ) as double);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> switchCamera(_i14.CameraDescription? camera) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchCamera,
          [camera],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i3.Photo> capturePhotoForActivity({
    required String? activityId,
    _i13.Coordinates? currentLocation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #capturePhotoForActivity,
          [],
          {
            #activityId: activityId,
            #currentLocation: currentLocation,
          },
        ),
        returnValue: _i11.Future<_i3.Photo>.value(_FakePhoto_1(
          this,
          Invocation.method(
            #capturePhotoForActivity,
            [],
            {
              #activityId: activityId,
              #currentLocation: currentLocation,
            },
          ),
        )),
      ) as _i11.Future<_i3.Photo>);

  @override
  _i11.Future<void> startPreview() => (super.noSuchMethod(
        Invocation.method(
          #startPreview,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> stopPreview() => (super.noSuchMethod(
        Invocation.method(
          #stopPreview,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setFlashMode(_i14.FlashMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setFlashMode,
          [mode],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setExposureMode(_i14.ExposureMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExposureMode,
          [mode],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setFocusMode(_i14.FocusMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setFocusMode,
          [mode],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setFocusPoint(_i15.Offset? point) => (super.noSuchMethod(
        Invocation.method(
          #setFocusPoint,
          [point],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setExposurePoint(_i15.Offset? point) => (super.noSuchMethod(
        Invocation.method(
          #setExposurePoint,
          [point],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setZoomLevel(double? zoom) => (super.noSuchMethod(
        Invocation.method(
          #setZoomLevel,
          [zoom],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [GpsDiagnosticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGpsDiagnosticsService extends _i1.Mock
    implements _i5.GpsDiagnosticsService {
  MockGpsDiagnosticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LocationService get locationService => (super.noSuchMethod(
        Invocation.getter(#locationService),
        returnValue: _FakeLocationService_2(
          this,
          Invocation.getter(#locationService),
        ),
      ) as _i4.LocationService);

  @override
  _i11.Future<_i5.GpsDiagnostics> getDiagnostics() => (super.noSuchMethod(
        Invocation.method(
          #getDiagnostics,
          [],
        ),
        returnValue:
            _i11.Future<_i5.GpsDiagnostics>.value(_FakeGpsDiagnostics_3(
          this,
          Invocation.method(
            #getDiagnostics,
            [],
          ),
        )),
      ) as _i11.Future<_i5.GpsDiagnostics>);

  @override
  _i11.Future<_i5.GpsTestResult> runGpsTest(
          {Duration? testDuration = const Duration(minutes: 1)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #runGpsTest,
          [],
          {#testDuration: testDuration},
        ),
        returnValue: _i11.Future<_i5.GpsTestResult>.value(_FakeGpsTestResult_4(
          this,
          Invocation.method(
            #runGpsTest,
            [],
            {#testDuration: testDuration},
          ),
        )),
      ) as _i11.Future<_i5.GpsTestResult>);

  @override
  _i11.Future<List<_i5.TroubleshootingStep>> getTroubleshootingSteps() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTroubleshootingSteps,
          [],
        ),
        returnValue: _i11.Future<List<_i5.TroubleshootingStep>>.value(
            <_i5.TroubleshootingStep>[]),
      ) as _i11.Future<List<_i5.TroubleshootingStep>>);
}

/// A class which mocks [CrashRecoveryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashRecoveryService extends _i1.Mock
    implements _i7.CrashRecoveryService {
  MockCrashRecoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ActivityTrackingService get activityTrackingService =>
      (super.noSuchMethod(
        Invocation.getter(#activityTrackingService),
        returnValue: _FakeActivityTrackingService_5(
          this,
          Invocation.getter(#activityTrackingService),
        ),
      ) as _i6.ActivityTrackingService);

  @override
  _i11.Future<void> saveSessionState({
    String? activeActivityId,
    bool? isTracking = false,
    DateTime? trackingStartTime,
    Map<String, dynamic>? additionalState,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSessionState,
          [],
          {
            #activeActivityId: activeActivityId,
            #isTracking: isTracking,
            #trackingStartTime: trackingStartTime,
            #additionalState: additionalState,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i7.CrashRecoveryResult> checkForCrashRecovery() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForCrashRecovery,
          [],
        ),
        returnValue: _i11.Future<_i7.CrashRecoveryResult>.value(
            _FakeCrashRecoveryResult_6(
          this,
          Invocation.method(
            #checkForCrashRecovery,
            [],
          ),
        )),
      ) as _i11.Future<_i7.CrashRecoveryResult>);

  @override
  _i11.Future<void> recoverTrackingSession(
    _i16.Activity? activity,
    Map<String, dynamic>? sessionData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverTrackingSession,
          [
            activity,
            sessionData,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> dismissRecovery() => (super.noSuchMethod(
        Invocation.method(
          #dismissRecovery,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> clearSessionState() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionState,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<Map<String, dynamic>> getDiagnosticInfo() => (super.noSuchMethod(
        Invocation.method(
          #getDiagnosticInfo,
          [],
        ),
        returnValue:
            _i11.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i11.Future<Map<String, dynamic>>);
}

/// A class which mocks [GracefulDegradationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGracefulDegradationService extends _i1.Mock
    implements _i10.GracefulDegradationService {
  MockGracefulDegradationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.PlatformPermissionService get permissionService => (super.noSuchMethod(
        Invocation.getter(#permissionService),
        returnValue: _FakePlatformPermissionService_7(
          this,
          Invocation.getter(#permissionService),
        ),
      ) as _i8.PlatformPermissionService);

  @override
  _i4.LocationService get locationService => (super.noSuchMethod(
        Invocation.getter(#locationService),
        returnValue: _FakeLocationService_2(
          this,
          Invocation.getter(#locationService),
        ),
      ) as _i4.LocationService);

  @override
  _i9.CameraService get cameraService => (super.noSuchMethod(
        Invocation.getter(#cameraService),
        returnValue: _FakeCameraService_8(
          this,
          Invocation.getter(#cameraService),
        ),
      ) as _i9.CameraService);

  @override
  _i11.Future<_i10.AppCapabilities> getAppCapabilities() => (super.noSuchMethod(
        Invocation.method(
          #getAppCapabilities,
          [],
        ),
        returnValue:
            _i11.Future<_i10.AppCapabilities>.value(_FakeAppCapabilities_9(
          this,
          Invocation.method(
            #getAppCapabilities,
            [],
          ),
        )),
      ) as _i11.Future<_i10.AppCapabilities>);

  @override
  _i11.Future<_i10.AlternativeFunctionality> getAlternativeFunctionality() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlternativeFunctionality,
          [],
        ),
        returnValue: _i11.Future<_i10.AlternativeFunctionality>.value(
            _FakeAlternativeFunctionality_10(
          this,
          Invocation.method(
            #getAlternativeFunctionality,
            [],
          ),
        )),
      ) as _i11.Future<_i10.AlternativeFunctionality>);

  @override
  _i11.Future<_i10.PermissionDenialResponse> handlePermissionDenial(
    _i10.PermissionType? permissionType,
    bool? isPermanentlyDenied,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePermissionDenial,
          [
            permissionType,
            isPermanentlyDenied,
          ],
        ),
        returnValue: _i11.Future<_i10.PermissionDenialResponse>.value(
            _FakePermissionDenialResponse_11(
          this,
          Invocation.method(
            #handlePermissionDenial,
            [
              permissionType,
              isPermanentlyDenied,
            ],
          ),
        )),
      ) as _i11.Future<_i10.PermissionDenialResponse>);

  @override
  _i11.Future<_i10.DegradedTrackingOptions> getDegradedTrackingOptions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDegradedTrackingOptions,
          [],
        ),
        returnValue: _i11.Future<_i10.DegradedTrackingOptions>.value(
            _FakeDegradedTrackingOptions_12(
          this,
          Invocation.method(
            #getDegradedTrackingOptions,
            [],
          ),
        )),
      ) as _i11.Future<_i10.DegradedTrackingOptions>);
}
