name: trailrun_app
description: A mobile app for trail runners to track runs, capture geo-tagged photos, and generate rich activity summaries.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Database & Storage
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Camera & Photos
  camera: ^0.10.5+5
  image: ^4.1.3
  exif: ^3.3.0
  
  # Networking
  dio: ^5.3.3
  connectivity_plus: ^5.0.2
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Charts
  fl_chart: ^0.65.0
  
  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  uuid: ^4.2.1
  share_plus: ^7.2.1
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  
  # Code Generation
  riverpod_generator: ^2.3.9
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # iOS specific configuration
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700
  
  # Generate app icons for iOS
  generate: true
