// Mocks generated by Mockito 5.4.6 from annotations
// in trailrun_app/test/presentation/providers/activity_history_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trailrun_app/domain/models/activity.dart' as _i2;
import 'package:trailrun_app/domain/models/track_point.dart' as _i5;
import 'package:trailrun_app/domain/repositories/activity_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeActivity_0 extends _i1.SmartFake implements _i2.Activity {
  _FakeActivity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityStats_1 extends _i1.SmartFake implements _i3.ActivityStats {
  _FakeActivityStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i1.Mock
    implements _i3.ActivityRepository {
  MockActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Activity> createActivity(_i2.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActivity,
          [activity],
        ),
        returnValue: _i4.Future<_i2.Activity>.value(_FakeActivity_0(
          this,
          Invocation.method(
            #createActivity,
            [activity],
          ),
        )),
      ) as _i4.Future<_i2.Activity>);

  @override
  _i4.Future<_i2.Activity> updateActivity(_i2.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActivity,
          [activity],
        ),
        returnValue: _i4.Future<_i2.Activity>.value(_FakeActivity_0(
          this,
          Invocation.method(
            #updateActivity,
            [activity],
          ),
        )),
      ) as _i4.Future<_i2.Activity>);

  @override
  _i4.Future<_i2.Activity?> getActivity(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivity,
          [activityId],
        ),
        returnValue: _i4.Future<_i2.Activity?>.value(),
      ) as _i4.Future<_i2.Activity?>);

  @override
  _i4.Future<_i2.Activity?> getActiveActivity() => (super.noSuchMethod(
        Invocation.method(
          #getActiveActivity,
          [],
        ),
        returnValue: _i4.Future<_i2.Activity?>.value(),
      ) as _i4.Future<_i2.Activity?>);

  @override
  _i4.Future<List<_i2.Activity>> getActivities({
    int? page = 0,
    int? pageSize = 20,
    _i3.ActivityFilter? filter,
    _i3.ActivitySortBy? sortBy = _i3.ActivitySortBy.startTimeDesc,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivities,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #filter: filter,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i4.Future<List<_i2.Activity>>.value(<_i2.Activity>[]),
      ) as _i4.Future<List<_i2.Activity>>);

  @override
  _i4.Future<int> getActivityCount({_i3.ActivityFilter? filter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityCount,
          [],
          {#filter: filter},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> deleteActivity(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #deleteActivity,
          [activityId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i2.Activity?> watchActivity(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActivity,
          [activityId],
        ),
        returnValue: _i4.Stream<_i2.Activity?>.empty(),
      ) as _i4.Stream<_i2.Activity?>);

  @override
  _i4.Stream<List<_i2.Activity>> watchActivities({
    _i3.ActivityFilter? filter,
    _i3.ActivitySortBy? sortBy = _i3.ActivitySortBy.startTimeDesc,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActivities,
          [],
          {
            #filter: filter,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i4.Stream<List<_i2.Activity>>.empty(),
      ) as _i4.Stream<List<_i2.Activity>>);

  @override
  _i4.Future<void> addTrackPoint(
    String? activityId,
    _i5.TrackPoint? trackPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTrackPoint,
          [
            activityId,
            trackPoint,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTrackPoints(
    String? activityId,
    List<_i5.TrackPoint>? trackPoints,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTrackPoints,
          [
            activityId,
            trackPoints,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TrackPoint>> getTrackPoints(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackPoints,
          [activityId],
        ),
        returnValue: _i4.Future<List<_i5.TrackPoint>>.value(<_i5.TrackPoint>[]),
      ) as _i4.Future<List<_i5.TrackPoint>>);

  @override
  _i4.Future<List<_i5.TrackPoint>> getTrackPointsInRange(
    String? activityId,
    DateTime? startTime,
    DateTime? endTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackPointsInRange,
          [
            activityId,
            startTime,
            endTime,
          ],
        ),
        returnValue: _i4.Future<List<_i5.TrackPoint>>.value(<_i5.TrackPoint>[]),
      ) as _i4.Future<List<_i5.TrackPoint>>);

  @override
  _i4.Future<void> deleteTrackPoints(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrackPoints,
          [activityId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Activity>> searchActivities(
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchActivities,
          [query],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.Activity>>.value(<_i2.Activity>[]),
      ) as _i4.Future<List<_i2.Activity>>);

  @override
  _i4.Future<List<_i2.Activity>> getActivitiesNeedingSync() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitiesNeedingSync,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Activity>>.value(<_i2.Activity>[]),
      ) as _i4.Future<List<_i2.Activity>>);

  @override
  _i4.Future<void> markActivitySynced(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markActivitySynced,
          [activityId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markActivitySyncFailed(
    String? activityId,
    String? error,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markActivitySyncFailed,
          [
            activityId,
            error,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.ActivityStats> getActivityStats({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityStats,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i3.ActivityStats>.value(_FakeActivityStats_1(
          this,
          Invocation.method(
            #getActivityStats,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i3.ActivityStats>);
}
