// Mocks generated by Mockito 5.4.6 from annotations
// in trailrun_app/test/presentation/widgets/share_export_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:share_plus/share_plus.dart' as _i2;
import 'package:trailrun_app/data/services/share_card_generator.dart' as _i9;
import 'package:trailrun_app/data/services/share_export_service.dart' as _i4;
import 'package:trailrun_app/domain/models/activity.dart' as _i6;
import 'package:trailrun_app/domain/models/photo.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeXFile_0 extends _i1.SmartFake implements _i2.XFile {
  _FakeXFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_1 extends _i1.SmartFake implements _i3.Widget {
  _FakeWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ShareExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareExportService extends _i1.Mock
    implements _i4.ShareExportService {
  MockShareExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> shareActivity(
    _i6.Activity? activity, {
    _i7.Uint8List? mapSnapshot,
    bool? includePhotos = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareActivity,
          [activity],
          {
            #mapSnapshot: mapSnapshot,
            #includePhotos: includePhotos,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sharePhoto(_i8.Photo? photo) => (super.noSuchMethod(
        Invocation.method(
          #sharePhoto,
          [photo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.XFile> exportActivityAsGpx(_i6.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportActivityAsGpx,
          [activity],
        ),
        returnValue: _i5.Future<_i2.XFile>.value(_FakeXFile_0(
          this,
          Invocation.method(
            #exportActivityAsGpx,
            [activity],
          ),
        )),
      ) as _i5.Future<_i2.XFile>);

  @override
  _i5.Future<List<_i2.XFile>> exportPhotoBundle(_i6.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportPhotoBundle,
          [activity],
        ),
        returnValue: _i5.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
      ) as _i5.Future<List<_i2.XFile>>);
}

/// A class which mocks [ShareCardGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareCardGenerator extends _i1.Mock
    implements _i9.ShareCardGenerator {
  MockShareCardGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Widget buildShareCard(
    _i6.Activity? activity, {
    _i7.Uint8List? mapSnapshot,
    List<_i7.Uint8List>? photoThumbnails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildShareCard,
          [activity],
          {
            #mapSnapshot: mapSnapshot,
            #photoThumbnails: photoThumbnails,
          },
        ),
        returnValue: _FakeWidget_1(
          this,
          Invocation.method(
            #buildShareCard,
            [activity],
            {
              #mapSnapshot: mapSnapshot,
              #photoThumbnails: photoThumbnails,
            },
          ),
        ),
      ) as _i3.Widget);

  @override
  _i5.Future<_i7.Uint8List?> renderShareCard(
    _i6.Activity? activity, {
    _i7.Uint8List? mapSnapshot,
    List<_i7.Uint8List>? photoThumbnails,
    double? pixelRatio = 2.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renderShareCard,
          [activity],
          {
            #mapSnapshot: mapSnapshot,
            #photoThumbnails: photoThumbnails,
            #pixelRatio: pixelRatio,
          },
        ),
        returnValue: _i5.Future<_i7.Uint8List?>.value(),
      ) as _i5.Future<_i7.Uint8List?>);

  @override
  _i5.Future<List<_i7.Uint8List>> loadPhotoThumbnails(
          List<_i8.Photo>? photos) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPhotoThumbnails,
          [photos],
        ),
        returnValue: _i5.Future<List<_i7.Uint8List>>.value(<_i7.Uint8List>[]),
      ) as _i5.Future<List<_i7.Uint8List>>);
}
