// Mocks generated by Mockito 5.4.6 from annotations
// in trailrun_app/test/data/services/graceful_degradation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i11;

import 'package:camera/camera.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trailrun_app/data/services/camera_service.dart' as _i9;
import 'package:trailrun_app/data/services/location_service.dart' as _i5;
import 'package:trailrun_app/data/services/platform_permission_service.dart'
    as _i4;
import 'package:trailrun_app/domain/models/photo.dart' as _i3;
import 'package:trailrun_app/domain/models/track_point.dart' as _i7;
import 'package:trailrun_app/domain/repositories/location_repository.dart'
    as _i2;
import 'package:trailrun_app/domain/value_objects/coordinates.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocationTrackingStats_0 extends _i1.SmartFake
    implements _i2.LocationTrackingStats {
  _FakeLocationTrackingStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhoto_1 extends _i1.SmartFake implements _i3.Photo {
  _FakePhoto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlatformPermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformPermissionService extends _i1.Mock
    implements _i4.PlatformPermissionService {
  MockPlatformPermissionService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i5.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocationTrackingState get trackingState => (super.noSuchMethod(
        Invocation.getter(#trackingState),
        returnValue: _i2.LocationTrackingState.stopped,
      ) as _i2.LocationTrackingState);

  @override
  _i6.Stream<_i7.TrackPoint> get locationStream => (super.noSuchMethod(
        Invocation.getter(#locationStream),
        returnValue: _i6.Stream<_i7.TrackPoint>.empty(),
      ) as _i6.Stream<_i7.TrackPoint>);

  @override
  _i6.Stream<_i2.LocationQuality> get locationQualityStream =>
      (super.noSuchMethod(
        Invocation.getter(#locationQualityStream),
        returnValue: _i6.Stream<_i2.LocationQuality>.empty(),
      ) as _i6.Stream<_i2.LocationQuality>);

  @override
  _i6.Stream<_i2.LocationTrackingState> get trackingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#trackingStateStream),
        returnValue: _i6.Stream<_i2.LocationTrackingState>.empty(),
      ) as _i6.Stream<_i2.LocationTrackingState>);

  @override
  bool get supportsBackgroundLocation => (super.noSuchMethod(
        Invocation.getter(#supportsBackgroundLocation),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.LocationPermissionStatus> getPermissionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPermissionStatus,
          [],
        ),
        returnValue: _i6.Future<_i2.LocationPermissionStatus>.value(
            _i2.LocationPermissionStatus.notRequested),
      ) as _i6.Future<_i2.LocationPermissionStatus>);

  @override
  _i6.Future<_i2.LocationPermissionStatus> requestPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i6.Future<_i2.LocationPermissionStatus>.value(
            _i2.LocationPermissionStatus.notRequested),
      ) as _i6.Future<_i2.LocationPermissionStatus>);

  @override
  _i6.Future<_i2.LocationPermissionStatus> requestBackgroundPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBackgroundPermission,
          [],
        ),
        returnValue: _i6.Future<_i2.LocationPermissionStatus>.value(
            _i2.LocationPermissionStatus.notRequested),
      ) as _i6.Future<_i2.LocationPermissionStatus>);

  @override
  _i6.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i8.Coordinates?> getCurrentLocation({
    _i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.balanced,
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
          {
            #accuracy: accuracy,
            #timeout: timeout,
          },
        ),
        returnValue: _i6.Future<_i8.Coordinates?>.value(),
      ) as _i6.Future<_i8.Coordinates?>);

  @override
  _i6.Future<void> startLocationTracking({
    _i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.balanced,
    int? intervalSeconds = 2,
    double? distanceFilter = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startLocationTracking,
          [],
          {
            #accuracy: accuracy,
            #intervalSeconds: intervalSeconds,
            #distanceFilter: distanceFilter,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #stopLocationTracking,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pauseLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #pauseLocationTracking,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resumeLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #resumeLocationTracking,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i8.Coordinates?> getLastKnownLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLastKnownLocation,
          [],
        ),
        returnValue: _i6.Future<_i8.Coordinates?>.value(),
      ) as _i6.Future<_i8.Coordinates?>);

  @override
  _i6.Future<bool> isHighAccuracyAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isHighAccuracyAvailable,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<double> getEstimatedBatteryUsage(_i2.LocationAccuracy? accuracy) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEstimatedBatteryUsage,
          [accuracy],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<void> configureFiltering({
    double? maxAccuracy = 50.0,
    double? maxSpeed = 50.0,
    bool? enableKalmanFilter = true,
    bool? enableOutlierDetection = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #configureFiltering,
          [],
          {
            #maxAccuracy: maxAccuracy,
            #maxSpeed: maxSpeed,
            #enableKalmanFilter: enableKalmanFilter,
            #enableOutlierDetection: enableOutlierDetection,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.LocationTrackingStats> getTrackingStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackingStats,
          [],
        ),
        returnValue: _i6.Future<_i2.LocationTrackingStats>.value(
            _FakeLocationTrackingStats_0(
          this,
          Invocation.method(
            #getTrackingStats,
            [],
          ),
        )),
      ) as _i6.Future<_i2.LocationTrackingStats>);

  @override
  _i6.Future<void> resetTrackingStats() => (super.noSuchMethod(
        Invocation.method(
          #resetTrackingStats,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setCurrentActivityId(String? activityId) => super.noSuchMethod(
        Invocation.method(
          #setCurrentActivityId,
          [activityId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraService extends _i1.Mock implements _i9.CameraService {
  MockCameraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isCapturing => (super.noSuchMethod(
        Invocation.getter(#isCapturing),
        returnValue: false,
      ) as bool);

  @override
  _i10.FlashMode get flashMode => (super.noSuchMethod(
        Invocation.getter(#flashMode),
        returnValue: _i10.FlashMode.off,
      ) as _i10.FlashMode);

  @override
  double get zoomLevel => (super.noSuchMethod(
        Invocation.getter(#zoomLevel),
        returnValue: 0.0,
      ) as double);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> switchCamera(_i10.CameraDescription? camera) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchCamera,
          [camera],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.Photo> capturePhotoForActivity({
    required String? activityId,
    _i8.Coordinates? currentLocation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #capturePhotoForActivity,
          [],
          {
            #activityId: activityId,
            #currentLocation: currentLocation,
          },
        ),
        returnValue: _i6.Future<_i3.Photo>.value(_FakePhoto_1(
          this,
          Invocation.method(
            #capturePhotoForActivity,
            [],
            {
              #activityId: activityId,
              #currentLocation: currentLocation,
            },
          ),
        )),
      ) as _i6.Future<_i3.Photo>);

  @override
  _i6.Future<void> startPreview() => (super.noSuchMethod(
        Invocation.method(
          #startPreview,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopPreview() => (super.noSuchMethod(
        Invocation.method(
          #stopPreview,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setFlashMode(_i10.FlashMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setFlashMode,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setExposureMode(_i10.ExposureMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExposureMode,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setFocusMode(_i10.FocusMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setFocusMode,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setFocusPoint(_i11.Offset? point) => (super.noSuchMethod(
        Invocation.method(
          #setFocusPoint,
          [point],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setExposurePoint(_i11.Offset? point) => (super.noSuchMethod(
        Invocation.method(
          #setExposurePoint,
          [point],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setZoomLevel(double? zoom) => (super.noSuchMethod(
        Invocation.method(
          #setZoomLevel,
          [zoom],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
