// Mocks generated by Mockito 5.4.6 from annotations
// in trailrun_app/test/presentation/screens/privacy_settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:trailrun_app/data/services/privacy_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PrivacyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrivacyService extends _i1.Mock implements _i2.PrivacyService {
  MockPrivacyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> stripPhotoExifData(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #stripPhotoExifData,
          [filePath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stripMultiplePhotosExifData(List<String>? filePaths) =>
      (super.noSuchMethod(
        Invocation.method(
          #stripMultiplePhotosExifData,
          [filePaths],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasExifData(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #hasExifData,
          [filePath],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getExifSummary(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExifSummary,
          [filePath],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> deleteAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllUserData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteActivityData(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteActivityData,
          [activityId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> exportUserDataWithPhotos() => (super.noSuchMethod(
        Invocation.method(
          #exportUserDataWithPhotos,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserDataWithPhotos,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> applyPrivacySettings(
    String? activityId,
    _i2.PrivacySettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyPrivacySettings,
          [
            activityId,
            settings,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
